In [64]:
import pandas as pd 
from sklearn.preprocessing import OneHotEncoder , LabelEncoder
from pandas import get_dummies
from numpy import array

In [1]:
df = pd.read_csv("df_clean.csv")

NameError: name 'pd' is not defined

In [ ]:
df

In [2]:
df.isnull().values.any()

NameError: name 'df' is not defined

In [3]:
df.duplicated().sum

NameError: name 'df' is not defined

In [4]:
df.plot(kind="box" , subplots=True , layout=(17,17) , figsize=(15,15))

NameError: name 'df' is not defined

Conclusion for the moment a lot of outliers no nan no duplicate
TotalGHGEmissions should be the target

In [70]:
df

,Unnamed: 0,OSEBuildingID,DataYear,BuildingType,PrimaryPropertyType,CouncilDistrictCode,Neighborhood,Latitude,Longitude,YearBuilt,...,ENERGYSTARScore,SiteEUI(kBtu/sf),SourceEUI(kBtu/sf),SiteEnergyUse(kBtu),SteamUse(kBtu),Electricity(kBtu),NaturalGas(kBtu),TotalGHGEmissions,GHGEmissionsIntensity,BuildingAge
0,0,1,2016,NonResidential,Hotel,7,DOWNTOWN,47.61220,-122.33799,1927,...,60.0,81.699997,182.500000,7.226362e+06,2003882.00,3.946027e+06,1.276453e+06,249.98,2.83,89
1,1,2,2016,NonResidential,Hotel,7,DOWNTOWN,47.61317,-122.33393,1996,...,61.0,94.800003,176.100006,8.387933e+06,0.00,3.242851e+06,5.145082e+06,295.86,2.86,20
2,2,3,2016,NonResidential,Hotel,7,DOWNTOWN,47.61393,-122.33810,1969,...,43.0,96.000000,241.899994,7.258702e+07,21566554.00,4.952666e+07,1.493800e+06,2089.28,2.19,47
3,3,5,2016,NonResidential,Hotel,7,DOWNTOWN,47.61412,-122.33664,1926,...,56.0,110.800003,216.199997,6.794584e+06,2214446.25,2.768924e+06,1.811213e+06,286.43,4.67,90
4,4,8,2016,NonResidential,Hotel,7,DOWNTOWN,47.61375,-122.34047,1980,...,75.0,114.800003,211.399994,1.417261e+07,0.00,5.368607e+06,8.803998e+06,505.01,2.88,36
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1663,3371,50222,2016,Nonresidential COS,Office,2,GREATER DUWAMISH,47.56722,-122.31154,1990,...,46.0,69.099998,161.699997,8.497457e+05,0.00,5.242709e+05,3.254750e+05,20.94,1.70,26
1664,3372,50223,2016,Nonresidential COS,Other,2,DOWNTOWN,47.59625,-122.32283,2004,...,NaN,59.400002,114.199997,9.502762e+05,0.00,3.965461e+05,5.537300e+05,32.17,2.01,12
1665,3373,50224,2016,Nonresidential COS,Other,7,MAGNOLIA / QUEEN ANNE,47.63644,-122.35784,1974,...,NaN,438.200012,744.799988,5.765898e+06,0.00,1.792159e+06,3.973739e+06,223.54,16.99,42
1666,3374,50225,2016,Nonresidential COS,Mixed Use Property,1,GREATER DUWAMISH,47.52832,-122.32431,1989,...,NaN,51.000000,105.300003,7.194712e+05,0.00,3.488702e+05,3.706010e+05,22.11,1.57,27
1667,3375,50226,2016,Nonresidential COS,Mixed Use Property,2,GREATER DUWAMISH,47.53939,-122.29536,1938,...,NaN,63.099998,115.800003,1.152896e+06,0.00,4.325542e+05,7.203420e+05,41.27,2.26,78

In [71]:
categ = ["GHGEmissionsIntensity","TotalGHGEmissions" , "NaturalGas(kBtu)", "NaturalGas(therms)", "Electricity(kBtu)", "NaturalGas(therms)", "Electricity(kWh)", "SteamUse(kBtu)", "SiteEnergyUseWN(kBtu)", "SiteEnergyUse(kBtu)" , "SourceEUIWN(kBtu/sf)","SourceEUI(kBtu/sf)","SiteEUIWN(kBtu/sf)","SiteEUI(kBtu/sf)","ENERGYSTARScore","LargestPropertyUseTypeGFA","ThirdLargestPropertyUseTypeGFA","YearsENERGYSTARCertified","OSEBuildingID" , "DataYear" , "ZipCode" , "TaxParcelIdentificationNumber" , "Latitude" , "Longitude" , "YearBuilt" , "NumberofBuildings" , "NumberofFloors" , "PropertyGFATotal" , "PropertyGFAParking" , "PropertyGFABuilding(s)" , "BuildingType" , "PrimaryPropertyType"  , "PropertyName", "Address" , "City"  , "State", "Neighborhood" , "ListOfAllPropertyUseTypes"  , "LargestPropertyUseType", "SecondLargestPropertyUseType" , "ThirdLargestPropertyUseType"  , "SecondLargestPropertyUseTypeGFA", "ComplianceStatus" , "DefaultData"  , "Comments", "ComplianceStatus" , "Outlier" , "NaturalGas(kBtu)" , "Electricity(kBtu)" , "Electricity(kWh)"]

In [75]:
df[categ] = df[categ].apply(le.fit_transform)

KeyError: "['PropertyName', 'SourceEUIWN(kBtu/sf)', 'State', 'ListOfAllPropertyUseTypes', 'Electricity(kWh)', 'ZipCode', 'TaxParcelIdentificationNumber', 'Outlier', 'ComplianceStatus', 'Address', 'DefaultData', 'NaturalGas(therms)', 'Comments', 'SiteEUIWN(kBtu/sf)', 'SiteEnergyUseWN(kBtu)', 'City', 'YearsENERGYSTARCertified'] not in index"

In [76]:
df

,Unnamed: 0,OSEBuildingID,DataYear,BuildingType,PrimaryPropertyType,CouncilDistrictCode,Neighborhood,Latitude,Longitude,YearBuilt,...,ENERGYSTARScore,SiteEUI(kBtu/sf),SourceEUI(kBtu/sf),SiteEnergyUse(kBtu),SteamUse(kBtu),Electricity(kBtu),NaturalGas(kBtu),TotalGHGEmissions,GHGEmissionsIntensity,BuildingAge
1,1,2,2016,NonResidential,Hotel,7,DOWNTOWN,47.61317,-122.33393,1996,...,61.0,94.800003,176.100006,8387933.0,0.0,3242851.0,5145082.0,295.86,2.86,20
4,4,8,2016,NonResidential,Hotel,7,DOWNTOWN,47.61375,-122.34047,1980,...,75.0,114.800003,211.399994,14172606.0,0.0,5368607.0,8803998.0,505.01,2.88,36
34,35,43,2016,Campus,Mixed Use Property,2,GREATER DUWAMISH,47.53493,-122.31788,1992,...,8.0,221.699997,388.200012,448385312.0,0.0,150476283.0,297909000.0,16870.98,34.09,24
43,44,57,2016,NonResidential,Large Office,7,DOWNTOWN,47.61130,-122.33659,1973,...,78.0,56.299999,176.600006,9536161.0,0.0,9536160.0,0.0,66.48,0.40,43
47,48,62,2016,NonResidential,Hotel,7,DOWNTOWN,47.61233,-122.33432,1930,...,71.0,54.599998,158.600006,4841347.5,0.0,4290059.0,551288.0,59.19,0.60,86
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1598,3192,49737,2016,NonResidential,Retail Store,7,MAGNOLIA / QUEEN ANNE,47.62503,-122.35642,1918,...,67.0,92.199997,163.500000,3886545.0,0.0,1343774.0,2542771.0,144.41,3.29,98
1601,3199,49776,2016,NonResidential,Large Office,7,DOWNTOWN,47.61156,-122.34401,1988,...,88.0,56.700001,167.699997,13458948.0,0.0,12288296.0,1170651.0,147.84,0.42,28
1609,3221,49802,2016,NonResidential,Hotel,6,BALLARD,47.66629,-122.38260,2013,...,62.0,58.000000,182.300003,3497215.5,0.0,3497215.0,0.0,24.38,0.39,3
1644,3329,50054,2016,Nonresidential COS,Large Office,7,LAKE UNION,47.62251,-122.33390,2014,...,98.0,37.900002,99.199997,13239050.0,0.0,9925769.0,3313279.0,245.16,0.46,2
1645,3337,50062,2016,NonResidential,Hotel,4,LAKE UNION,47.65476,-122.34732,2014,...,72.0,68.500000,169.500000,6042399.5,0.0,4115620.0,1926779.0,131.02,1.03,2

In [73]:
df.dropna(inplace=True)

In [74]:
df

,Unnamed: 0,OSEBuildingID,DataYear,BuildingType,PrimaryPropertyType,CouncilDistrictCode,Neighborhood,Latitude,Longitude,YearBuilt,...,ENERGYSTARScore,SiteEUI(kBtu/sf),SourceEUI(kBtu/sf),SiteEnergyUse(kBtu),SteamUse(kBtu),Electricity(kBtu),NaturalGas(kBtu),TotalGHGEmissions,GHGEmissionsIntensity,BuildingAge
1,1,2,2016,NonResidential,Hotel,7,DOWNTOWN,47.61317,-122.33393,1996,...,61.0,94.800003,176.100006,8387933.0,0.0,3242851.0,5145082.0,295.86,2.86,20
4,4,8,2016,NonResidential,Hotel,7,DOWNTOWN,47.61375,-122.34047,1980,...,75.0,114.800003,211.399994,14172606.0,0.0,5368607.0,8803998.0,505.01,2.88,36
34,35,43,2016,Campus,Mixed Use Property,2,GREATER DUWAMISH,47.53493,-122.31788,1992,...,8.0,221.699997,388.200012,448385312.0,0.0,150476283.0,297909000.0,16870.98,34.09,24
43,44,57,2016,NonResidential,Large Office,7,DOWNTOWN,47.61130,-122.33659,1973,...,78.0,56.299999,176.600006,9536161.0,0.0,9536160.0,0.0,66.48,0.40,43
47,48,62,2016,NonResidential,Hotel,7,DOWNTOWN,47.61233,-122.33432,1930,...,71.0,54.599998,158.600006,4841347.5,0.0,4290059.0,551288.0,59.19,0.60,86
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1598,3192,49737,2016,NonResidential,Retail Store,7,MAGNOLIA / QUEEN ANNE,47.62503,-122.35642,1918,...,67.0,92.199997,163.500000,3886545.0,0.0,1343774.0,2542771.0,144.41,3.29,98
1601,3199,49776,2016,NonResidential,Large Office,7,DOWNTOWN,47.61156,-122.34401,1988,...,88.0,56.700001,167.699997,13458948.0,0.0,12288296.0,1170651.0,147.84,0.42,28
1609,3221,49802,2016,NonResidential,Hotel,6,BALLARD,47.66629,-122.38260,2013,...,62.0,58.000000,182.300003,3497215.5,0.0,3497215.0,0.0,24.38,0.39,3
1644,3329,50054,2016,Nonresidential COS,Large Office,7,LAKE UNION,47.62251,-122.33390,2014,...,98.0,37.900002,99.199997,13239050.0,0.0,9925769.0,3313279.0,245.16,0.46,2
1645,3337,50062,2016,NonResidential,Hotel,4,LAKE UNION,47.65476,-122.34732,2014,...,72.0,68.500000,169.500000,6042399.5,0.0,4115620.0,1926779.0,131.02,1.03,2

In [59]:
df.to_csv("test.csv")

In [60]:
numericColumns = ['OSEBuildingID', 'CouncilDistrictCode',  'NumberofFloors','PropertyGFATotal', 'PropertyGFAParking', 'PropertyGFABuilding(s)', 'BuildingAge']
qualitativesColumns = list(df.select_dtypes(include=['object']))

In [63]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 159 entries, 1 to 1645
Data columns (total 31 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Unnamed: 0                       159 non-null    int64
 1   OSEBuildingID                    159 non-null    int64
 2   DataYear                         159 non-null    int64
 3   BuildingType                     159 non-null    object
 4   PrimaryPropertyType              159 non-null    object
 5   CouncilDistrictCode              159 non-null    int64
 6   Neighborhood                     159 non-null    object
 7   Latitude                         159 non-null    float64
 8   Longitude                        159 non-null    float64
 9   YearBuilt                        159 non-null    int64
 10  NumberofBuildings                159 non-null    float64
 11  NumberofFloors                   159 non-null    int64
 12  PropertyGFATotal                 159 non-null    int64
 13  PropertyGFAParking               159 non-null    int64
 14  PropertyGFABuilding(s)           159 non-null    int64
 15  LargestPropertyUseType           159 non-null    object
 16  LargestPropertyUseTypeGFA        159 non-null    float64
 17  SecondLargestPropertyUseType     159 non-null    object
 18  SecondLargestPropertyUseTypeGFA  159 non-null    float64
 19  ThirdLargestPropertyUseType      159 non-null    object
 20  ThirdLargestPropertyUseTypeGFA   159 non-null    float64
 21  ENERGYSTARScore                  159 non-null    float64
 22  SiteEUI(kBtu/sf)                 159 non-null    float64
 23  SourceEUI(kBtu/sf)               159 non-null    float64
 24  SiteEnergyUse(kBtu)              159 non-null    float64
 25  SteamUse(kBtu)                   159 non-null    float64
 26  Electricity(kBtu)                159 non-null    float64
 27  NaturalGas(kBtu)                 159 non-null    float64
 28  TotalGHGEmissions                159 non-null    float64
 29  GHGEmissionsIntensity            159 non-null    float64
 30  BuildingAge                      159 non-null    int64
dtypes: float64(15), int64(10), object(6)
memory usage: 39.8+ KB